/********************************************************************
* BeamDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BeamDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBeamDict();
extern void G__cpp_setup_inheritanceBeamDict();
extern void G__cpp_setup_typetableBeamDict();
extern void G__cpp_setup_memvarBeamDict();
extern void G__cpp_setup_globalBeamDict();
extern void G__cpp_setup_memfuncBeamDict();
extern void G__cpp_setup_funcBeamDict();
extern void G__set_cpp_environmentBeamDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LukeBeam.h"
#include "LukeBPM.h"
#include "LukeRaster.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BeamDictLN_TClass;
extern G__linked_taginfo G__BeamDictLN_TBuffer;
extern G__linked_taginfo G__BeamDictLN_TMemberInspector;
extern G__linked_taginfo G__BeamDictLN_TObject;
extern G__linked_taginfo G__BeamDictLN_TNamed;
extern G__linked_taginfo G__BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictLN_TDatime;
extern G__linked_taginfo G__BeamDictLN_THaEvData;
extern G__linked_taginfo G__BeamDictLN_TVector3;
extern G__linked_taginfo G__BeamDictLN_THaAnalysisObject;
extern G__linked_taginfo G__BeamDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictLN_THaDetector;
extern G__linked_taginfo G__BeamDictLN_THaApparatus;
extern G__linked_taginfo G__BeamDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BeamDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BeamDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BeamDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BeamDictLN_THaBeam;
extern G__linked_taginfo G__BeamDictLN_THaBeamModule;
extern G__linked_taginfo G__BeamDictLN_LukeBeam;
extern G__linked_taginfo G__BeamDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__BeamDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictLN_THaDetectorBase;
extern G__linked_taginfo G__BeamDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictLN_THaBeamDet;
extern G__linked_taginfo G__BeamDictLN_LukeBPM;
extern G__linked_taginfo G__BeamDictLN_LukeRaster;

/* STUB derived class for protected member access */
