/********************************************************************
* Tritium_XscinDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Tritium_XscinDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTritium_XscinDict();
extern void G__cpp_setup_inheritanceTritium_XscinDict();
extern void G__cpp_setup_typetableTritium_XscinDict();
extern void G__cpp_setup_memvarTritium_XscinDict();
extern void G__cpp_setup_globalTritium_XscinDict();
extern void G__cpp_setup_memfuncTritium_XscinDict();
extern void G__cpp_setup_funcTritium_XscinDict();
extern void G__set_cpp_environmentTritium_XscinDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Tritium_Xscin.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Tritium_XscinDictLN_TClass;
extern G__linked_taginfo G__Tritium_XscinDictLN_TBuffer;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMemberInspector;
extern G__linked_taginfo G__Tritium_XscinDictLN_TObject;
extern G__linked_taginfo G__Tritium_XscinDictLN_TNamed;
extern G__linked_taginfo G__Tritium_XscinDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TClonesArray;
extern G__linked_taginfo G__Tritium_XscinDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TDatime;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaEvData;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaAnalysisObject;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__Tritium_XscinDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaDetectorBase;
extern G__linked_taginfo G__Tritium_XscinDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaApparatus;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaDetector;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaSpectrometerDetector;
extern G__linked_taginfo G__Tritium_XscinDictLN_THaNonTrackingDetector;
extern G__linked_taginfo G__Tritium_XscinDictLN_Tritium_Xscin;
extern G__linked_taginfo G__Tritium_XscinDictLN_Tritium_XscincLcLDataDest;
extern G__linked_taginfo G__Tritium_XscinDictLN_Tritium_XscincLcLESide;

/* STUB derived class for protected member access */
