/********************************************************************
* Gmp_Track_ElossDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Gmp_Track_ElossDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGmp_Track_ElossDict();
extern void G__cpp_setup_inheritanceGmp_Track_ElossDict();
extern void G__cpp_setup_typetableGmp_Track_ElossDict();
extern void G__cpp_setup_memvarGmp_Track_ElossDict();
extern void G__cpp_setup_globalGmp_Track_ElossDict();
extern void G__cpp_setup_memfuncGmp_Track_ElossDict();
extern void G__cpp_setup_funcGmp_Track_ElossDict();
extern void G__set_cpp_environmentGmp_Track_ElossDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Gmp_Track_Eloss.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TClass;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TBuffer;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMemberInspector;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TObject;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TNamed;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TDatime;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaEvData;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaAnalysisObject;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaPhysicsModule;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaElossCorrection;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaTrackInfo;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_THaTrackingModule;
extern G__linked_taginfo G__Gmp_Track_ElossDictLN_Gmp_Track_Eloss;

/* STUB derived class for protected member access */
