/********************************************************************
* NormAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NormAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNormAnaDict();
extern void G__cpp_setup_inheritanceNormAnaDict();
extern void G__cpp_setup_typetableNormAnaDict();
extern void G__cpp_setup_memvarNormAnaDict();
extern void G__cpp_setup_globalNormAnaDict();
extern void G__cpp_setup_memfuncNormAnaDict();
extern void G__cpp_setup_funcNormAnaDict();
extern void G__set_cpp_environmentNormAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "THaNormAna.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NormAnaDictLN_TClass;
extern G__linked_taginfo G__NormAnaDictLN_TBuffer;
extern G__linked_taginfo G__NormAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__NormAnaDictLN_TObject;
extern G__linked_taginfo G__NormAnaDictLN_TNamed;
extern G__linked_taginfo G__NormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAnaDictLN_THaRunBase;
extern G__linked_taginfo G__NormAnaDictLN_TDatime;
extern G__linked_taginfo G__NormAnaDictLN_THaEvData;
extern G__linked_taginfo G__NormAnaDictLN_THaAnalysisObject;
extern G__linked_taginfo G__NormAnaDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__NormAnaDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__NormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__NormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAnaDictLN_THaPhysicsModule;
extern G__linked_taginfo G__NormAnaDictLN_TBits;
extern G__linked_taginfo G__NormAnaDictLN_THaScaler;
extern G__linked_taginfo G__NormAnaDictLN_BNormData;
extern G__linked_taginfo G__NormAnaDictLN_THaNormAna;
extern G__linked_taginfo G__NormAnaDictLN_vectorlEBRocScalermUcOallocatorlEBRocScalermUgRsPgR;
extern G__linked_taginfo G__NormAnaDictLN_reverse_iteratorlEvectorlEBRocScalermUcOallocatorlEBRocScalermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__NormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
