/********************************************************************
* TritiumDetMapDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TritiumDetMapDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTritiumDetMapDict();
extern void G__cpp_setup_inheritanceTritiumDetMapDict();
extern void G__cpp_setup_typetableTritiumDetMapDict();
extern void G__cpp_setup_memvarTritiumDetMapDict();
extern void G__cpp_setup_globalTritiumDetMapDict();
extern void G__cpp_setup_memfuncTritiumDetMapDict();
extern void G__cpp_setup_funcTritiumDetMapDict();
extern void G__set_cpp_environmentTritiumDetMapDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TritiumDetMap.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TritiumDetMapDictLN_TClass;
extern G__linked_taginfo G__TritiumDetMapDictLN_TBuffer;
extern G__linked_taginfo G__TritiumDetMapDictLN_TMemberInspector;
extern G__linked_taginfo G__TritiumDetMapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TritiumDetMapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TritiumDetMapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TritiumDetMapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TritiumDetMapDictLN_TritiumDetMap;
extern G__linked_taginfo G__TritiumDetMapDictLN_TritiumDetMapcLcLModule;
extern G__linked_taginfo G__TritiumDetMapDictLN_TritiumDetMapcLcLECountMode;
extern G__linked_taginfo G__TritiumDetMapDictLN_TritiumDetMapcLcLEFillFlags;
extern G__linked_taginfo G__TritiumDetMapDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TritiumDetMapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
