//
// File generated by /adaqfs/apps/ROOT/pro/bin/rootcint at Fri Feb 24 12:08:01 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Gmp_Rastered_BeamDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Gmp_Rastered_BeamDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void Gmp_Rastered_Beam_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_Gmp_Rastered_Beam(void *p);
   static void deleteArray_Gmp_Rastered_Beam(void *p);
   static void destruct_Gmp_Rastered_Beam(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Gmp_Rastered_Beam*)
   {
      ::Gmp_Rastered_Beam *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Gmp_Rastered_Beam >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Gmp_Rastered_Beam", ::Gmp_Rastered_Beam::Class_Version(), "./Gmp_Rastered_Beam.h", 12,
                  typeid(::Gmp_Rastered_Beam), ::ROOT::DefineBehavior(ptr, ptr),
                  &::Gmp_Rastered_Beam::Dictionary, isa_proxy, 4,
                  sizeof(::Gmp_Rastered_Beam) );
      instance.SetDelete(&delete_Gmp_Rastered_Beam);
      instance.SetDeleteArray(&deleteArray_Gmp_Rastered_Beam);
      instance.SetDestructor(&destruct_Gmp_Rastered_Beam);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Gmp_Rastered_Beam*)
   {
      return GenerateInitInstanceLocal((::Gmp_Rastered_Beam*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Gmp_Rastered_Beam*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void Gmp_BPM_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_Gmp_BPM(void *p);
   static void deleteArray_Gmp_BPM(void *p);
   static void destruct_Gmp_BPM(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Gmp_BPM*)
   {
      ::Gmp_BPM *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Gmp_BPM >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Gmp_BPM", ::Gmp_BPM::Class_Version(), "./Gmp_BPM.h", 13,
                  typeid(::Gmp_BPM), ::ROOT::DefineBehavior(ptr, ptr),
                  &::Gmp_BPM::Dictionary, isa_proxy, 4,
                  sizeof(::Gmp_BPM) );
      instance.SetDelete(&delete_Gmp_BPM);
      instance.SetDeleteArray(&deleteArray_Gmp_BPM);
      instance.SetDestructor(&destruct_Gmp_BPM);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Gmp_BPM*)
   {
      return GenerateInitInstanceLocal((::Gmp_BPM*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Gmp_BPM*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void Gmp_Raster_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_Gmp_Raster(void *p);
   static void deleteArray_Gmp_Raster(void *p);
   static void destruct_Gmp_Raster(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Gmp_Raster*)
   {
      ::Gmp_Raster *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Gmp_Raster >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Gmp_Raster", ::Gmp_Raster::Class_Version(), "./Gmp_Raster.h", 13,
                  typeid(::Gmp_Raster), ::ROOT::DefineBehavior(ptr, ptr),
                  &::Gmp_Raster::Dictionary, isa_proxy, 4,
                  sizeof(::Gmp_Raster) );
      instance.SetDelete(&delete_Gmp_Raster);
      instance.SetDeleteArray(&deleteArray_Gmp_Raster);
      instance.SetDestructor(&destruct_Gmp_Raster);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Gmp_Raster*)
   {
      return GenerateInitInstanceLocal((::Gmp_Raster*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Gmp_Raster*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr Gmp_Rastered_Beam::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Gmp_Rastered_Beam::Class_Name()
{
   return "Gmp_Rastered_Beam";
}

//______________________________________________________________________________
const char *Gmp_Rastered_Beam::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Rastered_Beam*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Gmp_Rastered_Beam::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Rastered_Beam*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Gmp_Rastered_Beam::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Rastered_Beam*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Gmp_Rastered_Beam::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Rastered_Beam*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr Gmp_BPM::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Gmp_BPM::Class_Name()
{
   return "Gmp_BPM";
}

//______________________________________________________________________________
const char *Gmp_BPM::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_BPM*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Gmp_BPM::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_BPM*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Gmp_BPM::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_BPM*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Gmp_BPM::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_BPM*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr Gmp_Raster::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Gmp_Raster::Class_Name()
{
   return "Gmp_Raster";
}

//______________________________________________________________________________
const char *Gmp_Raster::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Raster*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Gmp_Raster::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Raster*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Gmp_Raster::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Raster*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Gmp_Raster::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Gmp_Raster*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void Gmp_Rastered_Beam::Streamer(TBuffer &R__b)
{
   // Stream an object of class Gmp_Rastered_Beam.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Gmp_Rastered_Beam::Class(),this);
   } else {
      R__b.WriteClassBuffer(Gmp_Rastered_Beam::Class(),this);
   }
}

//______________________________________________________________________________
void Gmp_Rastered_Beam::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Gmp_Rastered_Beam.
      TClass *R__cl = ::Gmp_Rastered_Beam::IsA();
      if (R__cl || R__insp.IsA()) { }
      THaBeam::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_Gmp_Rastered_Beam(void *p) {
      delete ((::Gmp_Rastered_Beam*)p);
   }
   static void deleteArray_Gmp_Rastered_Beam(void *p) {
      delete [] ((::Gmp_Rastered_Beam*)p);
   }
   static void destruct_Gmp_Rastered_Beam(void *p) {
      typedef ::Gmp_Rastered_Beam current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Gmp_Rastered_Beam

//______________________________________________________________________________
void Gmp_BPM::Streamer(TBuffer &R__b)
{
   // Stream an object of class Gmp_BPM.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Gmp_BPM::Class(),this);
   } else {
      R__b.WriteClassBuffer(Gmp_BPM::Class(),this);
   }
}

//______________________________________________________________________________
void Gmp_BPM::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Gmp_BPM.
      TClass *R__cl = ::Gmp_BPM::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRawSignal", &fRawSignal);
      R__insp.InspectMember(fRawSignal, "fRawSignal.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPedestals", &fPedestals);
      R__insp.InspectMember(fPedestals, "fPedestals.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCorSignal", &fCorSignal);
      R__insp.InspectMember(fCorSignal, "fCorSignal.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRotPos", &fRotPos);
      R__insp.InspectMember(fRotPos, "fRotPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRot2HCSPos", &fRot2HCSPos);
      R__insp.InspectMember(fRot2HCSPos, "fRot2HCSPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fOffset", &fOffset);
      R__insp.InspectMember(fOffset, "fOffset.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosition", &fPosition);
      R__insp.InspectMember(fPosition, "fPosition.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDirection", &fDirection);
      R__insp.InspectMember(fDirection, "fDirection.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNfired", &fNfired);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCalibRot", &fCalibRot);
      THaBeamDet::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_Gmp_BPM(void *p) {
      delete ((::Gmp_BPM*)p);
   }
   static void deleteArray_Gmp_BPM(void *p) {
      delete [] ((::Gmp_BPM*)p);
   }
   static void destruct_Gmp_BPM(void *p) {
      typedef ::Gmp_BPM current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Gmp_BPM

//______________________________________________________________________________
void Gmp_Raster::Streamer(TBuffer &R__b)
{
   // Stream an object of class Gmp_Raster.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Gmp_Raster::Class(),this);
   } else {
      R__b.WriteClassBuffer(Gmp_Raster::Class(),this);
   }
}

//______________________________________________________________________________
void Gmp_Raster::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Gmp_Raster.
      TClass *R__cl = ::Gmp_Raster::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRawPos", &fRawPos);
      R__insp.InspectMember(fRawPos, "fRawPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRawSlope", &fRawSlope);
      R__insp.InspectMember(fRawSlope, "fRawSlope.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosition[3]", fPosition);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDirection", &fDirection);
      R__insp.InspectMember(fDirection, "fDirection.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRaw2Pos[3]", fRaw2Pos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosOff[3]", fPosOff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRasterFreq", &fRasterFreq);
      R__insp.InspectMember(fRasterFreq, "fRasterFreq.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSlopePedestal", &fSlopePedestal);
      R__insp.InspectMember(fSlopePedestal, "fSlopePedestal.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRasterPedestal", &fRasterPedestal);
      R__insp.InspectMember(fRasterPedestal, "fRasterPedestal.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNfired", &fNfired);
      THaBeamDet::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_Gmp_Raster(void *p) {
      delete ((::Gmp_Raster*)p);
   }
   static void deleteArray_Gmp_Raster(void *p) {
      delete [] ((::Gmp_Raster*)p);
   }
   static void destruct_Gmp_Raster(void *p) {
      typedef ::Gmp_Raster current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Gmp_Raster

/********************************************************
* Gmp_Rastered_BeamDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGmp_Rastered_BeamDict();

extern "C" void G__set_cpp_environmentGmp_Rastered_BeamDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Gmp_Rastered_Beam.h");
  G__add_compiledheader("Gmp_BPM.h");
  G__add_compiledheader("Gmp_Raster.h");
  G__cpp_reset_tagtableGmp_Rastered_BeamDict();
}
#include <new>
extern "C" int G__cpp_dllrevGmp_Rastered_BeamDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Gmp_Rastered_Beam */
static int G__Gmp_Rastered_BeamDict_251_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Gmp_Rastered_Beam* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Gmp_Rastered_Beam((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) Gmp_Rastered_Beam((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Gmp_Rastered_Beam::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_Rastered_Beam::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Gmp_Rastered_Beam::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Gmp_Rastered_Beam::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Gmp_Rastered_Beam*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_Rastered_Beam::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gmp_Rastered_Beam::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_Rastered_Beam::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_251_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gmp_Rastered_Beam::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Gmp_Rastered_Beam G__TGmp_Rastered_Beam;
static int G__Gmp_Rastered_BeamDict_251_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Gmp_Rastered_Beam*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Gmp_Rastered_Beam*) (soff+(sizeof(Gmp_Rastered_Beam)*i)))->~G__TGmp_Rastered_Beam();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Gmp_Rastered_Beam*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Gmp_Rastered_Beam*) (soff))->~G__TGmp_Rastered_Beam();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Gmp_BPM */
static int G__Gmp_Rastered_BeamDict_293_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Gmp_BPM* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gmp_BPM(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (THaApparatus*) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) Gmp_BPM(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (THaApparatus*) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gmp_BPM((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) Gmp_BPM((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gmp_BPM((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) Gmp_BPM((const char*) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_BPM*) G__getstructoffset())->GetRawSignal0());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_BPM*) G__getstructoffset())->GetRawSignal1());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_BPM*) G__getstructoffset())->GetRawSignal2());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_BPM*) G__getstructoffset())->GetRawSignal3());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_BPM*) G__getstructoffset())->GetRotPosX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_BPM*) G__getstructoffset())->GetRotPosY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Gmp_BPM::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_BPM::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Gmp_BPM::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Gmp_BPM::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Gmp_BPM*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_BPM::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gmp_BPM::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_BPM::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_293_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gmp_BPM::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Gmp_BPM G__TGmp_BPM;
static int G__Gmp_Rastered_BeamDict_293_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Gmp_BPM*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Gmp_BPM*) (soff+(sizeof(Gmp_BPM)*i)))->~G__TGmp_BPM();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Gmp_BPM*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Gmp_BPM*) (soff))->~G__TGmp_BPM();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Gmp_Raster */
static int G__Gmp_Rastered_BeamDict_294_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Gmp_Raster* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gmp_Raster(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (THaApparatus*) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) Gmp_Raster(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (THaApparatus*) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gmp_Raster((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) Gmp_Raster((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gmp_Raster((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) Gmp_Raster((const char*) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetRawPosX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetRawPosY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetRawSlopeX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetRawSlopeY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosBPMAX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosBPMAY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosBPMAZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosBPMBX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosBPMBY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosBPMBZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosTarX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosTarY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Gmp_Raster*) G__getstructoffset())->GetPosTarZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Gmp_Raster::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_Raster::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Gmp_Raster::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Gmp_Raster::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Gmp_Raster*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_Raster::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gmp_Raster::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gmp_Raster::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Gmp_Rastered_BeamDict_294_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gmp_Raster::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Gmp_Raster G__TGmp_Raster;
static int G__Gmp_Rastered_BeamDict_294_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Gmp_Raster*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Gmp_Raster*) (soff+(sizeof(Gmp_Raster)*i)))->~G__TGmp_Raster();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Gmp_Raster*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Gmp_Raster*) (soff))->~G__TGmp_Raster();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Gmp_Rastered_Beam */

/* Gmp_BPM */

/* Gmp_Raster */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGmp_Rastered_BeamDict {
 public:
  G__Sizep2memfuncGmp_Rastered_BeamDict(): p(&G__Sizep2memfuncGmp_Rastered_BeamDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGmp_Rastered_BeamDict::*p)();
};

size_t G__get_sizep2memfuncGmp_Rastered_BeamDict()
{
  G__Sizep2memfuncGmp_Rastered_BeamDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGmp_Rastered_BeamDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam))) {
     Gmp_Rastered_Beam *G__Lderived;
     G__Lderived=(Gmp_Rastered_Beam*)0x1000;
     {
       THaBeam *G__Lpbase=(THaBeam*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaBeam),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       THaApparatus *G__Lpbase=(THaApparatus*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaApparatus),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THaAnalysisObject *G__Lpbase=(THaAnalysisObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaAnalysisObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THaBeamModule *G__Lpbase=(THaBeamModule*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaBeamModule),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM))) {
     Gmp_BPM *G__Lderived;
     G__Lderived=(Gmp_BPM*)0x1000;
     {
       THaBeamDet *G__Lpbase=(THaBeamDet*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaBeamDet),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       THaDetector *G__Lpbase=(THaDetector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaDetector),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THaDetectorBase *G__Lpbase=(THaDetectorBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaDetectorBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THaAnalysisObject *G__Lpbase=(THaAnalysisObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaAnalysisObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster))) {
     Gmp_Raster *G__Lderived;
     G__Lderived=(Gmp_Raster*)0x1000;
     {
       THaBeamDet *G__Lpbase=(THaBeamDet*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaBeamDet),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       THaDetector *G__Lpbase=(THaDetector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaDetector),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THaDetectorBase *G__Lpbase=(THaDetectorBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaDetectorBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THaAnalysisObject *G__Lpbase=(THaAnalysisObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_THaAnalysisObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGmp_Rastered_BeamDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Gmp_Rastered_Beam */
static void G__setup_memvarGmp_Rastered_Beam(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam));
   { Gmp_Rastered_Beam *p; p=(Gmp_Rastered_Beam*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* Gmp_BPM */
static void G__setup_memvarGmp_BPM(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM));
   { Gmp_BPM *p; p=(Gmp_BPM*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fRawSignal=",0,"induced signal of the antennas");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fPedestals=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fCorSignal=",0,"pedestal subtracted signal");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fRotPos=",0,"position in the BPM system, arbitrary units");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR),G__defined_typename("TMatrix"),-1,2,"fRot2HCSPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3),-1,-1,2,"fOffset=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3),-1,-1,2,"fPosition=",0,"Beam position at the BPM (meters)");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3),-1,-1,2,"fDirection=",0,"Beam direction at the BPM");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fNfired=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fCalibRot=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* Gmp_Raster */
static void G__setup_memvarGmp_Raster(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster));
   { Gmp_Raster *p; p=(Gmp_Raster*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fRawPos=",0,"current in Raster ADCs for position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fRawSlope=",0,"current in Raster ADCs for the derivative");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3),-1,-1,2,"fPosition[3]=",0,"Beam position at 1st, 2nd BPM or at the target (meters)");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3),-1,-1,2,"fDirection=",0,"Beam angle at the target (meters)");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR),G__defined_typename("TMatrix"),-1,2,"fRaw2Pos[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3),-1,-1,2,"fPosOff[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fRasterFreq=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fSlopePedestal=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR),G__defined_typename("TVector"),-1,2,"fRasterPedestal=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fNfired=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGmp_Rastered_BeamDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGmp_Rastered_Beam(void) {
   /* Gmp_Rastered_Beam */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam));
   G__memfunc_setup("Gmp_Rastered_Beam",1681,G__Gmp_Rastered_BeamDict_251_0_1, 105, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam), -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - description", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reconstruct",1180,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__Gmp_Rastered_BeamDict_251_0_3, 85, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Gmp_Rastered_Beam::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Gmp_Rastered_BeamDict_251_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_Rastered_Beam::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Gmp_Rastered_BeamDict_251_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Gmp_Rastered_Beam::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Gmp_Rastered_BeamDict_251_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Gmp_Rastered_Beam::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Gmp_Rastered_BeamDict_251_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Gmp_Rastered_BeamDict_251_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_Rastered_Beam::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Gmp_Rastered_BeamDict_251_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gmp_Rastered_Beam::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Gmp_Rastered_BeamDict_251_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_Rastered_Beam::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Gmp_Rastered_BeamDict_251_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gmp_Rastered_Beam::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Gmp_Rastered_Beam", 1807, G__Gmp_Rastered_BeamDict_251_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncGmp_BPM(void) {
   /* Gmp_BPM */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM));
   G__memfunc_setup("Gmp_BPM",610,G__Gmp_Rastered_BeamDict_293_0_1, 105, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM), -1, 0, 3, 1, 1, 0, 
"C - - 10 - name C - - 10 '\"\"' description "
"U 'THaApparatus' - 0 'NULL' a", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Decode",580,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "u 'THaEvData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPosition",1141,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDirection",1217,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRawSignal0",1240,G__Gmp_Rastered_BeamDict_293_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRawSignal1",1241,G__Gmp_Rastered_BeamDict_293_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRawSignal2",1242,G__Gmp_Rastered_BeamDict_293_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRawSignal3",1243,G__Gmp_Rastered_BeamDict_293_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRotPosX",991,G__Gmp_Rastered_BeamDict_293_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRotPosY",992,G__Gmp_Rastered_BeamDict_293_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearEvent",1001,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDatabase",1169,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 2, 0, "u 'TDatime' - 11 - date", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DefineVariables",1508,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 2, 0, "i 'THaAnalysisObject::EMode' - 0 'kDefine' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM), -1, 1, 1, 1, 2, 0, "u 'Gmp_BPM' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Gmp_Rastered_BeamDict_293_0_16, 85, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Gmp_BPM::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Gmp_Rastered_BeamDict_293_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_BPM::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Gmp_Rastered_BeamDict_293_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Gmp_BPM::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Gmp_Rastered_BeamDict_293_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Gmp_BPM::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Gmp_Rastered_BeamDict_293_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Gmp_Rastered_BeamDict_293_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_BPM::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Gmp_Rastered_BeamDict_293_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gmp_BPM::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Gmp_Rastered_BeamDict_293_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_BPM::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Gmp_Rastered_BeamDict_293_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gmp_BPM::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Gmp_BPM", 736, G__Gmp_Rastered_BeamDict_293_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncGmp_Raster(void) {
   /* Gmp_Raster */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster));
   G__memfunc_setup("Gmp_Raster",1012,G__Gmp_Rastered_BeamDict_294_0_1, 105, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster), -1, 0, 3, 1, 1, 0, 
"C - - 10 - name C - - 10 '\"\"' description "
"U 'THaApparatus' - 0 'NULL' a", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Decode",580,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "u 'THaEvData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPosition",1141,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDirection",1217,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TVector3), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRawPosX",980,G__Gmp_Rastered_BeamDict_294_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRawPosY",981,G__Gmp_Rastered_BeamDict_294_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRawSlopeX",1189,G__Gmp_Rastered_BeamDict_294_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRawSlopeY",1190,G__Gmp_Rastered_BeamDict_294_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosBPMAX",970,G__Gmp_Rastered_BeamDict_294_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosBPMAY",971,G__Gmp_Rastered_BeamDict_294_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosBPMAZ",972,G__Gmp_Rastered_BeamDict_294_0_12, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosBPMBX",971,G__Gmp_Rastered_BeamDict_294_0_13, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosBPMBY",972,G__Gmp_Rastered_BeamDict_294_0_14, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosBPMBZ",973,G__Gmp_Rastered_BeamDict_294_0_15, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosTarX",977,G__Gmp_Rastered_BeamDict_294_0_16, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosTarY",978,G__Gmp_Rastered_BeamDict_294_0_17, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosTarZ",979,G__Gmp_Rastered_BeamDict_294_0_18, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearEvent",1001,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDatabase",1169,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 2, 0, "u 'TDatime' - 11 - date", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DefineVariables",1508,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 2, 0, "i 'THaAnalysisObject::EMode' - 0 'kDefine' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster), -1, 1, 1, 1, 2, 0, "u 'Gmp_Raster' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Gmp_Rastered_BeamDict_294_0_23, 85, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Gmp_Raster::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Gmp_Rastered_BeamDict_294_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_Raster::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Gmp_Rastered_BeamDict_294_0_25, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Gmp_Raster::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Gmp_Rastered_BeamDict_294_0_26, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Gmp_Raster::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Gmp_Rastered_BeamDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Gmp_Rastered_BeamDict_294_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Gmp_Rastered_BeamDict_294_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_Raster::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Gmp_Rastered_BeamDict_294_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gmp_Raster::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Gmp_Rastered_BeamDict_294_0_33, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gmp_Raster::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Gmp_Rastered_BeamDict_294_0_34, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gmp_Raster::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Gmp_Raster", 1138, G__Gmp_Rastered_BeamDict_294_0_35, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGmp_Rastered_BeamDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGmp_Rastered_BeamDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGmp_Rastered_BeamDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TDatime = { "TDatime" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaEvData = { "THaEvData" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaAnalysisObject = { "THaAnalysisObject" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaAnalysisObjectcLcLEMode = { "THaAnalysisObject::EMode" , 101 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaDetector = { "THaDetector" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaApparatus = { "THaApparatus" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaBeam = { "THaBeam" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaBeamModule = { "THaBeamModule" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam = { "Gmp_Rastered_Beam" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaDetectorBase = { "THaDetectorBase" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaBeamDet = { "THaBeamDet" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_Gmp_BPM = { "Gmp_BPM" , 99 , -1 };
G__linked_taginfo G__Gmp_Rastered_BeamDictLN_Gmp_Raster = { "Gmp_Raster" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGmp_Rastered_BeamDict() {
  G__Gmp_Rastered_BeamDictLN_TClass.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TBuffer.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMemberInspector.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TObject.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TNamed.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TDatime.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaEvData.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TVector3.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaAnalysisObject.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaAnalysisObjectcLcLEMode.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaDetector.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaApparatus.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaBeam.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaBeamModule.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaDetectorBase.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_THaBeamDet.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_Gmp_BPM.tagnum = -1 ;
  G__Gmp_Rastered_BeamDictLN_Gmp_Raster.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGmp_Rastered_BeamDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TDatime);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaEvData);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaAnalysisObject);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaAnalysisObjectcLcLEMode);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaDetector);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaApparatus);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaBeam);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaBeamModule);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam),sizeof(Gmp_Rastered_Beam),-1,324608,"A beam with rastered beam, analyzed event by event using raster currents",G__setup_memvarGmp_Rastered_Beam,G__setup_memfuncGmp_Rastered_Beam);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaDetectorBase);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_THaBeamDet);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_Gmp_BPM),sizeof(Gmp_BPM),-1,326656,"Generic BPM class",G__setup_memvarGmp_BPM,G__setup_memfuncGmp_BPM);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Gmp_Rastered_BeamDictLN_Gmp_Raster),sizeof(Gmp_Raster),-1,326656,"Generic Raster class",G__setup_memvarGmp_Raster,G__setup_memfuncGmp_Raster);
}
extern "C" void G__cpp_setupGmp_Rastered_BeamDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGmp_Rastered_BeamDict()");
  G__set_cpp_environmentGmp_Rastered_BeamDict();
  G__cpp_setup_tagtableGmp_Rastered_BeamDict();

  G__cpp_setup_inheritanceGmp_Rastered_BeamDict();

  G__cpp_setup_typetableGmp_Rastered_BeamDict();

  G__cpp_setup_memvarGmp_Rastered_BeamDict();

  G__cpp_setup_memfuncGmp_Rastered_BeamDict();
  G__cpp_setup_globalGmp_Rastered_BeamDict();
  G__cpp_setup_funcGmp_Rastered_BeamDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGmp_Rastered_BeamDict();
  return;
}
class G__cpp_setup_initGmp_Rastered_BeamDict {
  public:
    G__cpp_setup_initGmp_Rastered_BeamDict() { G__add_setup_func("Gmp_Rastered_BeamDict",(G__incsetup)(&G__cpp_setupGmp_Rastered_BeamDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGmp_Rastered_BeamDict() { G__remove_setup_func("Gmp_Rastered_BeamDict"); }
};
G__cpp_setup_initGmp_Rastered_BeamDict G__cpp_setup_initializerGmp_Rastered_BeamDict;

