/********************************************************************
* Gmp_Rastered_BeamDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Gmp_Rastered_BeamDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGmp_Rastered_BeamDict();
extern void G__cpp_setup_inheritanceGmp_Rastered_BeamDict();
extern void G__cpp_setup_typetableGmp_Rastered_BeamDict();
extern void G__cpp_setup_memvarGmp_Rastered_BeamDict();
extern void G__cpp_setup_globalGmp_Rastered_BeamDict();
extern void G__cpp_setup_memfuncGmp_Rastered_BeamDict();
extern void G__cpp_setup_funcGmp_Rastered_BeamDict();
extern void G__set_cpp_environmentGmp_Rastered_BeamDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Gmp_Rastered_Beam.h"
#include "Gmp_BPM.h"
#include "Gmp_Raster.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TClass;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TBuffer;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMemberInspector;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TObject;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TNamed;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TDatime;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaEvData;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TVector3;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaAnalysisObject;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaDetector;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaApparatus;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaBeam;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaBeamModule;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_Gmp_Rastered_Beam;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaDetectorBase;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_THaBeamDet;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_Gmp_BPM;
extern G__linked_taginfo G__Gmp_Rastered_BeamDictLN_Gmp_Raster;

/* STUB derived class for protected member access */
