//
// File generated by /adaqfs/apps/ROOT/pro/bin/rootcint at Fri Feb 24 10:40:17 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME GmpNormAnaDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GmpNormAnaDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void GmpNormAna_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GmpNormAna(void *p = 0);
   static void *newArray_GmpNormAna(Long_t size, void *p);
   static void delete_GmpNormAna(void *p);
   static void deleteArray_GmpNormAna(void *p);
   static void destruct_GmpNormAna(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::GmpNormAna*)
   {
      ::GmpNormAna *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GmpNormAna >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GmpNormAna", ::GmpNormAna::Class_Version(), "./GmpNormAna.h", 143,
                  typeid(::GmpNormAna), ::ROOT::DefineBehavior(ptr, ptr),
                  &::GmpNormAna::Dictionary, isa_proxy, 4,
                  sizeof(::GmpNormAna) );
      instance.SetNew(&new_GmpNormAna);
      instance.SetNewArray(&newArray_GmpNormAna);
      instance.SetDelete(&delete_GmpNormAna);
      instance.SetDeleteArray(&deleteArray_GmpNormAna);
      instance.SetDestructor(&destruct_GmpNormAna);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::GmpNormAna*)
   {
      return GenerateInitInstanceLocal((::GmpNormAna*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GmpNormAna*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr GmpNormAna::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *GmpNormAna::Class_Name()
{
   return "GmpNormAna";
}

//______________________________________________________________________________
const char *GmpNormAna::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::GmpNormAna*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GmpNormAna::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::GmpNormAna*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GmpNormAna::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::GmpNormAna*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GmpNormAna::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::GmpNormAna*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void GmpNormAna::Streamer(TBuffer &R__b)
{
   // Stream an object of class GmpNormAna.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GmpNormAna::Class(),this);
   } else {
      R__b.WriteClassBuffer(GmpNormAna::Class(),this);
   }
}

//______________________________________________________________________________
void GmpNormAna::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GmpNormAna.
      TClass *R__cl = ::GmpNormAna::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*myscaler", &myscaler);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*normdata", &normdata);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSpectr", &fSpectr);
      R__insp.InspectMember(fSpectr, "fSpectr.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "herecnt", &herecnt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSetPrescale", &fSetPrescale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHelEnable", &fHelEnable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDoBcmCalib", &fDoBcmCalib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evtypebits", &evtypebits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tdcdata", &tdcdata);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nhit", &nhit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t1live", &t1live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t2live", &t2live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t3live", &t3live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t4live", &t4live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t5live", &t5live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t6live", &t6live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t7live", &t7live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t8live", &t8live);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_u1", &bcm_u1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_u3", &bcm_u3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_u10", &bcm_u10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_d1", &bcm_d1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_d3", &bcm_d3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_d10", &bcm_d10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_unew", &bcm_unew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcm_dnew", &bcm_dnew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_u1", &charge_u1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_u3", &charge_u3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_u10", &charge_u10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_d1", &charge_d1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_d3", &charge_d3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_d10", &charge_d10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_unew", &charge_unew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_dnew", &charge_dnew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_u1", &off_u1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_u3", &off_u3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_u10", &off_u10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_d1", &off_d1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_d3", &off_d3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_d10", &off_d10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_unew", &off_unew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "off_dnew", &off_dnew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_u1", &gain_u1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_u3", &gain_u3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_u10", &gain_u10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_d1", &gain_d1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_d3", &gain_d3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_d10", &gain_d10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_unew", &gain_unew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain_dnew", &gain_dnew);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSLive1", &TSLive1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSLive2", &TSLive2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSdtime", &TSdtime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "crate", &crate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "slot", &slot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "startchan", &startchan);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "scaroc", &scaroc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "header", &header);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hist", (void*)&hist);
      R__insp.InspectMember("vector<TH1*>", (void*)&hist, "hist.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*outputFile", &outputFile);
      THaPhysicsModule::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_GmpNormAna(void *p) {
      return  p ? new(p) ::GmpNormAna : new ::GmpNormAna;
   }
   static void *newArray_GmpNormAna(Long_t nElements, void *p) {
      return p ? new(p) ::GmpNormAna[nElements] : new ::GmpNormAna[nElements];
   }
   // Wrapper around operator delete
   static void delete_GmpNormAna(void *p) {
      delete ((::GmpNormAna*)p);
   }
   static void deleteArray_GmpNormAna(void *p) {
      delete [] ((::GmpNormAna*)p);
   }
   static void destruct_GmpNormAna(void *p) {
      typedef ::GmpNormAna current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::GmpNormAna

/********************************************************
* GmpNormAnaDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGmpNormAnaDict();

extern "C" void G__set_cpp_environmentGmpNormAnaDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("GmpNormAna.h");
  G__cpp_reset_tagtableGmpNormAnaDict();
}
#include <new>
extern "C" int G__cpp_dllrevGmpNormAnaDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GmpNormAna */
static int G__GmpNormAnaDict_215_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GmpNormAna* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GmpNormAna((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) GmpNormAna((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GmpNormAna((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) GmpNormAna((const char*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new GmpNormAna[n];
       } else {
         p = new((void*) gvp) GmpNormAna[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new GmpNormAna;
       } else {
         p = new((void*) gvp) GmpNormAna;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GmpNormAna*) G__getstructoffset())->WriteHist();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GmpNormAna*) G__getstructoffset())->Reconstruct());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const GmpNormAna*) G__getstructoffset())->PrintSummary());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GmpNormAna::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GmpNormAna::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GmpNormAna::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GmpNormAna::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GmpNormAna*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GmpNormAna::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GmpNormAna::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GmpNormAna::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GmpNormAnaDict_215_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GmpNormAna::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GmpNormAna G__TGmpNormAna;
static int G__GmpNormAnaDict_215_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GmpNormAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GmpNormAna*) (soff+(sizeof(GmpNormAna)*i)))->~G__TGmpNormAna();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GmpNormAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GmpNormAna*) (soff))->~G__TGmpNormAna();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GmpNormAna */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGmpNormAnaDict {
 public:
  G__Sizep2memfuncGmpNormAnaDict(): p(&G__Sizep2memfuncGmpNormAnaDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGmpNormAnaDict::*p)();
};

size_t G__get_sizep2memfuncGmpNormAnaDict()
{
  G__Sizep2memfuncGmpNormAnaDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGmpNormAnaDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna))) {
     GmpNormAna *G__Lderived;
     G__Lderived=(GmpNormAna*)0x1000;
     {
       THaPhysicsModule *G__Lpbase=(THaPhysicsModule*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna),G__get_linked_tagnum(&G__GmpNormAnaDictLN_THaPhysicsModule),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       THaAnalysisObject *G__Lpbase=(THaAnalysisObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna),G__get_linked_tagnum(&G__GmpNormAnaDictLN_THaAnalysisObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna),G__get_linked_tagnum(&G__GmpNormAnaDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna),G__get_linked_tagnum(&G__GmpNormAnaDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGmpNormAnaDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1*>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GmpNormAna */
static void G__setup_memvarGmpNormAna(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna));
   { GmpNormAna *p; p=(GmpNormAna*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_THaScaler),-1,-1,4,"myscaler=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_BNormData),-1,-1,4,"normdata=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_TString),-1,-1,4,"fSpectr=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"herecnt=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fSetPrescale=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fHelEnable=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fDoBcmCalib=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"evtypebits=",0,"trigger bit pattern");
   G__memvar_setup((void*)0,73,0,0,-1,G__defined_typename("Int_t"),-1,4,"tdcdata=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,G__defined_typename("Int_t"),-1,4,"nhit=",0,"tdc for trigger bit");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t1live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t2live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t3live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t4live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t5live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t6live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t7live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"t8live=",0,"scaler livetime");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_u1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_u3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_u10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_d1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_d3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_d10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_unew=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"bcm_dnew=",0,"Beam current");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_u1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_u3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_u10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_d1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_d3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_d10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_unew=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"charge_dnew=",0,"Integrated charge");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_u1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_u3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_u10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_d1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_d3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_d10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_unew=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"off_dnew=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_u1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_u3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_u10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_d1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_d3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_d10=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_unew=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"gain_dnew=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"TSLive1=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"TSLive2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"TSdtime=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"crate=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"slot=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"startchan=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"scaroc=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"header=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR),G__defined_typename("vector<TH1*>"),-1,4,"hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ofstream"),-1,4,"outputFile=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,4,"fgNumRoc=2LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,4,"fgNumChan=32LL",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GmpNormAnaDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGmpNormAnaDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGmpNormAna(void) {
   /* GmpNormAna */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna));
   G__memfunc_setup("GmpNormAna",976,G__GmpNormAnaDict_215_0_1, 105, G__get_linked_tagnum(&G__GmpNormAnaDictLN_GmpNormAna), -1, 0, 2, 1, 1, 0, 
"C - - 10 '\"N\"' name C - - 10 '\"Normalizion Analysis\"' description", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, G__get_linked_tagnum(&G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEStatus), -1, 0, 1, 1, 1, 0, "u 'TDatime' - 11 - run_time", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'THaRunBase' - 0 '0' r", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("WriteHist",931,G__GmpNormAnaDict_215_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reconstruct",1180,G__GmpNormAnaDict_215_0_5, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "u 'THaEvData' - 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintSummary",1275,G__GmpNormAnaDict_215_0_7, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 8, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("TrigBits",808,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - - 0 - helicity", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LiveTime",799,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcCharge",957,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DefineVariables",1508,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 4, 0, "i 'THaAnalysisObject::EMode' - 0 'kDefine' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BookHist",803,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MakePrefix",1004,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDBFileName",1191,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 0, 1, 4, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ReadDatabase",1169,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 4, 0, "u 'TDatime' - 11 - date", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GmpNormAnaDict_215_0_17, 85, G__get_linked_tagnum(&G__GmpNormAnaDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GmpNormAna::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GmpNormAnaDict_215_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GmpNormAna::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GmpNormAnaDict_215_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GmpNormAna::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GmpNormAnaDict_215_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GmpNormAna::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GmpNormAnaDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GmpNormAnaDict_215_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GmpNormAnaDict_215_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GmpNormAna::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GmpNormAnaDict_215_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GmpNormAna::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GmpNormAnaDict_215_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GmpNormAna::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GmpNormAnaDict_215_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GmpNormAna::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~GmpNormAna", 1102, G__GmpNormAnaDict_215_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGmpNormAnaDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGmpNormAnaDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGmpNormAnaDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GmpNormAnaDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR = { "basic_ofstream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaRunBase = { "THaRunBase" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_TDatime = { "TDatime" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaEvData = { "THaEvData" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaAnalysisObject = { "THaAnalysisObject" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEStatus = { "THaAnalysisObject::EStatus" , 101 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEMode = { "THaAnalysisObject::EMode" , 101 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaPhysicsModule = { "THaPhysicsModule" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_THaScaler = { "THaScaler" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_BNormData = { "BNormData" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_GmpNormAna = { "GmpNormAna" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR = { "vector<TH1*,allocator<TH1*> >" , 99 , -1 };
G__linked_taginfo G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1*,allocator<TH1*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGmpNormAnaDict() {
  G__GmpNormAnaDictLN_TClass.tagnum = -1 ;
  G__GmpNormAnaDictLN_TBuffer.tagnum = -1 ;
  G__GmpNormAnaDictLN_TMemberInspector.tagnum = -1 ;
  G__GmpNormAnaDictLN_TObject.tagnum = -1 ;
  G__GmpNormAnaDictLN_TNamed.tagnum = -1 ;
  G__GmpNormAnaDictLN_TString.tagnum = -1 ;
  G__GmpNormAnaDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaRunBase.tagnum = -1 ;
  G__GmpNormAnaDictLN_TDatime.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaEvData.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaAnalysisObject.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEStatus.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEMode.tagnum = -1 ;
  G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaPhysicsModule.tagnum = -1 ;
  G__GmpNormAnaDictLN_THaScaler.tagnum = -1 ;
  G__GmpNormAnaDictLN_BNormData.tagnum = -1 ;
  G__GmpNormAnaDictLN_GmpNormAna.tagnum = -1 ;
  G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR.tagnum = -1 ;
  G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGmpNormAnaDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaRunBase);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_TDatime);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaEvData);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaAnalysisObject);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEStatus);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaAnalysisObjectcLcLEMode);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaPhysicsModule);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_THaScaler);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_BNormData);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_GmpNormAna),sizeof(GmpNormAna),-1,324864,"Normalization analysis utilities",G__setup_memvarGmpNormAna,G__setup_memfuncGmpNormAna);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GmpNormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupGmpNormAnaDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGmpNormAnaDict()");
  G__set_cpp_environmentGmpNormAnaDict();
  G__cpp_setup_tagtableGmpNormAnaDict();

  G__cpp_setup_inheritanceGmpNormAnaDict();

  G__cpp_setup_typetableGmpNormAnaDict();

  G__cpp_setup_memvarGmpNormAnaDict();

  G__cpp_setup_memfuncGmpNormAnaDict();
  G__cpp_setup_globalGmpNormAnaDict();
  G__cpp_setup_funcGmpNormAnaDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGmpNormAnaDict();
  return;
}
class G__cpp_setup_initGmpNormAnaDict {
  public:
    G__cpp_setup_initGmpNormAnaDict() { G__add_setup_func("GmpNormAnaDict",(G__incsetup)(&G__cpp_setupGmpNormAnaDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGmpNormAnaDict() { G__remove_setup_func("GmpNormAnaDict"); }
};
G__cpp_setup_initGmpNormAnaDict G__cpp_setup_initializerGmpNormAnaDict;

