#!/bin/bash
currentdir=`pwd`



case $1 in 
"" | "last")
    runnum=`cat ~adaq/datafile/rcRunNumberL`
    CFILE=/adaq1/data1/triton_$runnum.dat.0
    if [ ! -f $CFILE ]
    then  CFILE=/adaq1/data1/triton_$runnum.dat.0
	 fi
	 if [ ! -f $CFILE ]
	 then CFILE=/chafs2/work1/Ar40/raw/triton_$runnum.dat.0
	 fi
    if [ "$CFILE" = "" ] 
    then
	echo "ERROR: no CODA files"
	exit
    fi
    
    if [ -s $CFILE ] 
    then
	echo "opening $CFILE"
    else
        echo "ERROR: $CFILE does not exist or is empty"
        exit
    fi
        
    if [ -z $2 ]
    then
      FIRST=1
      LAST=50000
    else
	if [ -z $3 ]
            then
              FIRST=1
              LAST=$2
            else
              FIRST=$2
              LAST=$3
        fi
    fi    
    ;;
"help" | "HELP" )
    echo "Usage:"
    echo "raster++ "
    echo "->   standard plots from the last coda run"
    echo "raster++ help "
    echo "->   prints this message"
    echo "raster++ #### "
    echo "->   standard plots from run ####"
    echo "raster++ last #1 #2 "
    echo "->   plots from last coda run, using events from #1 to #2"
    echo "raster++ #### #1 #2 "
    echo "->   plots from coda run ####, using events from #1 to #2"
    echo "in all cases a new root file is generated, overwriting "
    echo "the previous one."
    echo "please communicate comments to reitz@jlab.org"
    echo " "
    exit;;
* )

    runnum=$1
    CFILE=/adaq1/data1/triton_$1.dat.0
    if [ ! -f $CFILE ]
    then  CFILE=/adaq1/data1/triton_$1.dat.0
    fi
	 if [ ! -f $CFILE ]
	 then CFILE=/chafs2/work1/Ar40/raw/triton_$1.dat.0
	 fi
    if [ "$CFILE" = "" ] 
    then
       echo "ERROR: no CODA files"
       exit
    fi

    if [ -s $CFILE ] 
    then
	echo "opening $CFILE"
    else
        echo "ERROR: $CFILE does not exist or is empty"
        exit
    fi

    if [ -z $2 ]
    then
      FIRST=1
      LAST=50000
    else
	if [ -z $3 ]
            then
              FIRST=1
              LAST=$2
            else
              FIRST=$2
              LAST=$3
        fi
    fi    
    ;;   

esac


cd /adaqfs/home/a-onl/tritium/replay/scripts/SPOT/LeftHRS_Tritium

export DB_DIR="/adaqfs/home/a-onl/tritium/replay/DB"

#rm -f rastersize.root

analyzer -b -q 'get_rastersize_L.C("'$CFILE'","'$runnum'",'$FIRST','$LAST',"rastersize.root")'

RootFILE=L$runnum".root"
spot_dir="/chafs1/work1/tritium/spot"

mv rastersize.root ${spot_dir}/$RootFILE
mv Tritium_$runnum.pdf ${spot_dir}/.
mv FADC_Tritium_$runnum.pdf ${spot_dir}/.

echo =================
echo DONE. PDFs and ROOTFILE are stored at ${spot_dir}
echo =================
echo "RUN : ${runnum}"
cd $currentdir
evince ${spot_dir}/Tritium_$runnum.pdf &
evince ${spot_dir}/FADC_Tritium_$runnum.pdf &

function yes_or_no {
  while true; do
    read -p "$* [y/n]: " yn
    case $yn in
      [Yy]*) return 0 ;;
      [Nn]*) echo "No entered" ; return 1 ;;
    esac
  done
}

yes_or_no "Upload these plots to logbook HALOG? " && \
/site/ace/certified/apps/bin/logentry \
    --logbook "HALOG" \
    --tag Autolog \
    --title "Spot check using Left HRS run ${runnum}" \
    --attach ${spot_dir}/Tritium_${runnum}.pdf \
    --attach ${spot_dir}/FADC_Tritium_${runnum}.pdf


