#!/bin/bash

if [ $# -eq 0 ] 
then
	echo "Please enter run number"
	read RUNNUM
else
	RUNNUM=$1
fi
if [ $RUNNUM -le 20000 ]
then
	
	HOST=`hostname -s`

	case "$HOST" in
	  aonl[1-4]| adaq1)

   	onlineGUI64/./online -f onlineGUI64/LHRS.cfg -r $RUNNUM

   	onlineGUI64/./online -f onlineGUI64/LHRS_phy.cfg -r $RUNNUM

  	;;

  	*)

  	onlineGUI64/./online -f onlineGUI64/LHRS.cfg -r $RUNNUM

  	onlineGUI64/./online -f onlineGUI64/LHRS_phy.cfg -r $RUNNUM
  	;;
	esac

else

	HOST=`hostname -s`

	case "$HOST" in
	  aonl[1-4]|adaq1)
    
   	onlineGUI64/./online -f onlineGUI64/RHRS.cfg -r $RUNNUM

   	onlineGUI64/./online -f onlineGUI64/RHRS_phy.cfg -r $RUNNUM

  	;;

  	*)

  	onlineGUI64/./online -f onlineGUI64/RHRS.cfg -r $1

  	onlineGUI64/./online -f onlineGUI64/RHRS_phy.cfg -r $1

  	;;
	esac
fi
