#!/bin/bash

if [ $# -eq 0 ] 
then
	echo "Please enter run number"
	read RUNNUM
else
	RUNNUM=$1
fi
if [ $RUNNUM -le 90000 ]
then
	
  	onlineGUI64/online -f onlineGUI64/LHRS.cfg -r $RUNNUM

  	onlineGUI64/online -f onlineGUI64/LHRS_phy.cfg -r $RUNNUM
  
else

  	onlineGUI64/online -f onlineGUI64/RHRS.cfg -r $RUNNUM

  	onlineGUI64/online -f onlineGUI64/RHRS_phy.cfg -r $RUNNUM

fi
