/********************************************************************
* Gmp_HRSDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Gmp_HRSDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGmp_HRSDict();
extern void G__cpp_setup_inheritanceGmp_HRSDict();
extern void G__cpp_setup_typetableGmp_HRSDict();
extern void G__cpp_setup_memvarGmp_HRSDict();
extern void G__cpp_setup_globalGmp_HRSDict();
extern void G__cpp_setup_memfuncGmp_HRSDict();
extern void G__cpp_setup_funcGmp_HRSDict();
extern void G__set_cpp_environmentGmp_HRSDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Gmp_HRS.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Gmp_HRSDictLN_TClass;
extern G__linked_taginfo G__Gmp_HRSDictLN_TBuffer;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMemberInspector;
extern G__linked_taginfo G__Gmp_HRSDictLN_TObject;
extern G__linked_taginfo G__Gmp_HRSDictLN_TNamed;
extern G__linked_taginfo G__Gmp_HRSDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TClonesArray;
extern G__linked_taginfo G__Gmp_HRSDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_THaAnalysisObject;
extern G__linked_taginfo G__Gmp_HRSDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_THaApparatus;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_THaVertexModule;
extern G__linked_taginfo G__Gmp_HRSDictLN_THaSpectrometer;
extern G__linked_taginfo G__Gmp_HRSDictLN_THaTrackingModule;
extern G__linked_taginfo G__Gmp_HRSDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Gmp_HRSDictLN_THaScintillator;
extern G__linked_taginfo G__Gmp_HRSDictLN_Gmp_HRS;

/* STUB derived class for protected member access */
