/********************************************************************
* FppDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FppDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFppDict();
extern void G__cpp_setup_inheritanceFppDict();
extern void G__cpp_setup_typetableFppDict();
extern void G__cpp_setup_memvarFppDict();
extern void G__cpp_setup_globalFppDict();
extern void G__cpp_setup_memfuncFppDict();
extern void G__cpp_setup_funcFppDict();
extern void G__set_cpp_environmentFppDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "THaFpp.h"
#include "THaFppPlane.h"
#include "THaFppHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FppDictLN_TClass;
extern G__linked_taginfo G__FppDictLN_TBuffer;
extern G__linked_taginfo G__FppDictLN_TMemberInspector;
extern G__linked_taginfo G__FppDictLN_TObject;
extern G__linked_taginfo G__FppDictLN_TNamed;
extern G__linked_taginfo G__FppDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FppDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FppDictLN_TClonesArray;
extern G__linked_taginfo G__FppDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FppDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FppDictLN_THaRunBase;
extern G__linked_taginfo G__FppDictLN_TDatime;
extern G__linked_taginfo G__FppDictLN_THaEvData;
extern G__linked_taginfo G__FppDictLN_THaAnalysisObject;
extern G__linked_taginfo G__FppDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__FppDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__FppDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__FppDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__FppDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__FppDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__FppDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__FppDictLN_THaDetectorBase;
extern G__linked_taginfo G__FppDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__FppDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FppDictLN_THaDetector;
extern G__linked_taginfo G__FppDictLN_THaApparatus;
extern G__linked_taginfo G__FppDictLN_THaSpectrometerDetector;
extern G__linked_taginfo G__FppDictLN_THaNonTrackingDetector;
extern G__linked_taginfo G__FppDictLN_THaFppPlane;
extern G__linked_taginfo G__FppDictLN_THaFpp;
extern G__linked_taginfo G__FppDictLN_THaSubDetector;
extern G__linked_taginfo G__FppDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FppDictLN_THaFppHit;

/* STUB derived class for protected member access */
