/********************************************************************
* Gmp_Beam_ElossDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Gmp_Beam_ElossDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGmp_Beam_ElossDict();
extern void G__cpp_setup_inheritanceGmp_Beam_ElossDict();
extern void G__cpp_setup_typetableGmp_Beam_ElossDict();
extern void G__cpp_setup_memvarGmp_Beam_ElossDict();
extern void G__cpp_setup_globalGmp_Beam_ElossDict();
extern void G__cpp_setup_memfuncGmp_Beam_ElossDict();
extern void G__cpp_setup_funcGmp_Beam_ElossDict();
extern void G__set_cpp_environmentGmp_Beam_ElossDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Gmp_Beam_Eloss.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TClass;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TBuffer;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMemberInspector;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TObject;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TNamed;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TDatime;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaEvData;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaAnalysisObject;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaPhysicsModule;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaElossCorrection;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaBeamInfo;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_THaBeamModule;
extern G__linked_taginfo G__Gmp_Beam_ElossDictLN_Gmp_Beam_Eloss;

/* STUB derived class for protected member access */
